### ISSUE TITLE
Windows上找不到OpenSSL

### ISSUE THREAD

**Issue by plmsuper8** [falseen/shadowsocks-pyqt#3]
首先很感谢做这个版本。不过它提示没安装openssl，于是我安装了以下版本的openssl（1.1e）
    http://slproweb.com/products/Win32OpenSSL.html
但是还是失败，即便把libcrypto.dll放到安装目录里也找不到。

日志如下：
shadowsocks-pyqt is started
2017-03-18 16:33:26 INFO     loading config from config.json
2017-03-18 16:33:26 ERROR    libcrypto(OpenSSL) not found

如果优先调用目录里的libcrypto，大概也能解决openssl的版本问题吧。

**Comment by falseen** [comment]
你的系统是64位还是32位，以及openssl是64位还是32位？ 如果你安装的openssl是64位的话尝试安装一下32位，或者把openssl卸了，然后把dll文件放到shadowsocks-pyqt目录中。

这其实是ss的一个小bug，它不是没找到dll，而是找到的版本其位数跟系统或python的位数不一致。

**Comment by falseen** [comment]
因为ss的优先调用系统环境变量中的目录去寻找的，所以如果你的系统中安装了其他版本的openssl或其他应用程序安装了openssl的dll的话，即使你把dll放到程序根目录也没用。它只有在系统环境变量中找寻失败后才会尝试在当前目录中找。

一个简单的办法是把这个项目中lib文件夹下的dll文件放到 system32 目录中，或确保电脑中没有其他openssl的情况下把dll文件放到程序目录，如果你不想折腾的话。后续会考虑把dll文件也打包进去。

**Comment by falseen** [comment]
@plmsuper8 
新版的ss存在一些问题，正在尝试修复，具体见这里：https://github.com/shadowsocks/shadowsocks/issues/783#issuecomment-287532407

优先从当前目录中查找dll的功能我已经做出来了，如果你是用python运行的话，更新源码即可（我这个项目）。晚点我再打包。

**Comment by plmsuper8** [comment]
谢谢，确实是openssl版本的问题，我最后用的1.0.2k 32bit：
    loading libcrypto from C:\WINDOWS\system32\libeay32.dll
